version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: datn-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    networks:
      - datn-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: datn-rabbitmq
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - datn-network

  postgres:
    image: postgres:15
    container_name: datn-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tlu_regulations
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - datn-network

networks:
  datn-network:
    driver: bridge
